### ISSUE TITLE
Npm install fail

### ISSUE THREAD

**Issue by arnesten** [robertkeizer/linux-util#2]
Seem to be hardcoded to local directory of creator: 

OSError: [Errno 2] No such file or directory: '/home/rob/src/linux-util/lib'
npm ERR! error installing linux-util@0.0.3-rc2 Error: linux-util@0.0.3-rc2 install: `node-waf configure clean build`
npm ERR! error installing linux-util@0.0.3-rc2 `sh "-c" "node-waf configure clean build"` failed with 1
npm ERR! error installing linux-util@0.0.3-rc2     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing linux-util@0.0.3-rc2     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing linux-util@0.0.3-rc2     at maybeExit (child_process.js:359:16)
npm ERR! error installing linux-util@0.0.3-rc2     at Process.onexit (child_process.js:395:5)

/Calle

**Comment by robertkeizer** [comment]
Ack my bad. Ill fix that up today.

Sent from a mobile device.
